# galay-kernel 构建选项配置

# IO后端选项
option(DISABLE_IOURING "Disable io_uring and use epoll on Linux" ON)

# 平台特定的异步IO后端检测
function(configure_io_backend)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        if(DISABLE_IOURING)
            message(STATUS "io_uring disabled by user, using epoll")
            add_compile_definitions(USE_EPOLL)
            # epoll 模式需要 libaio 支持异步文件IO
            find_library(AIO_LIB aio)
            if(AIO_LIB)
                message(STATUS "Found libaio: ${AIO_LIB}")
                set(PLATFORM_LIBS ${AIO_LIB} PARENT_SCOPE)
            else()
                message(WARNING "libaio not found, async file IO will not work")
            endif()
        else()
            find_library(URING_LIB uring)
            if(URING_LIB)
                message(STATUS "Found liburing: ${URING_LIB}, using io_uring")
                add_compile_definitions(USE_IOURING)
                set(PLATFORM_LIBS ${URING_LIB} PARENT_SCOPE)
            else()
                message(STATUS "liburing not found, falling back to epoll")
                add_compile_definitions(USE_EPOLL)
                # fallback 到 epoll 时也需要 libaio
                find_library(AIO_LIB aio)
                if(AIO_LIB)
                    set(PLATFORM_LIBS ${AIO_LIB} PARENT_SCOPE)
                endif()
            endif()
        endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        message(STATUS "macOS detected, using kqueue")
        add_compile_definitions(USE_KQUEUE)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        message(STATUS "Windows detected, using IOCP")
        add_compile_definitions(USE_IOCP)
    else()
        message(WARNING "Unknown platform: ${CMAKE_SYSTEM_NAME}")
    endif()
endfunction()
